# Generated by Django 4.2.7 on 2024-08-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=300)),
                ('secret_key', models.CharField(max_length=300)),
                ('endpoint_secret', models.CharField(max_length=300)),
            ],
        ),
    ]
