# Generated by Django 4.2.7 on 2024-05-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripekeys',
            name='endpoint_secret',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stripekeys',
            name='public_key',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='stripekeys',
            name='secret_key',
            field=models.CharField(max_length=300),
        ),
    ]
