# Generated by Django 4.2.7 on 2024-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_purchase_purchaseproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={},
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='payment_purpose',
            field=models.CharField(default='N/A', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bic',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='iban',
            field=models.CharField(max_length=255),
        ),
    ]
