# Generated by Django 4.2.7 on 2024-09-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_bankdetails_options_bankdetails_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='payment_purpose',
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_purpose',
            field=models.CharField(default='N/A', max_length=255, unique=True),
        ),
    ]
