# Generated by Django 4.2.7 on 2024-09-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_purchaseproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetails',
            old_name='bic',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='iban',
        ),
    ]
