# Generated by Django 4.2.7 on 2024-10-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_rename_bic_bankdetails_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('INTERNETBANKA', 'Internetbanka'), ('BANK_TRANSFER', 'Bankas pārskaitījums'), ('APPLE_PAY', 'Apple Pay'), ('STRIPE', 'Stripe')], default='INTERNETBANKA', max_length=20),
        ),
    ]
