# Generated by Django 4.2.7 on 2025-06-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0002_productinventory_and_more'),
        ('payments', '0011_giftcode_purchase_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseproduct',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_details.size'),
            preserve_default=False,
        ),
    ]
