# Generated by Django 4.2.7 on 2025-06-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0002_productinventory_and_more'),
        ('payments', '0012_purchaseproduct_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseproduct',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_details.size'),
        ),
    ]
