# Generated by Django 4.2.7 on 2024-08-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0001_initial'),
        ('design', '0002_alter_designs_options_remove_designs_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_details.color'),
        ),
    ]
