# Generated by Django 4.2.7 on 2024-09-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_designs_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designs',
            name='description',
        ),
    ]
