# Generated by Django 4.2.7 on 2025-06-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_remove_designs_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designs',
            name='average_rating',
        ),
    ]
