# Generated by Django 4.2.7 on 2024-08-14 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ievadiet kategorijas nosaukumu.', max_length=100, unique=True, verbose_name='Virsraksts')),
                ('title_lv', models.CharField(help_text='Ievadiet kategorijas nosaukumu.', max_length=100, null=True, unique=True, verbose_name='Virsraksts')),
                ('title_en', models.CharField(help_text='Ievadiet kategorijas nosaukumu.', max_length=100, null=True, unique=True, verbose_name='Virsraksts')),
                ('slug', models.SlugField(blank=True, help_text='Ievadiet URL draudzīgu nosaukumu.', unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Bilde')),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorijas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ievadiet produkta nosaukumu.', max_length=100, unique=True, verbose_name='Virsraksts')),
                ('title_lv', models.CharField(help_text='Ievadiet produkta nosaukumu.', max_length=100, null=True, unique=True, verbose_name='Virsraksts')),
                ('title_en', models.CharField(help_text='Ievadiet produkta nosaukumu.', max_length=100, null=True, unique=True, verbose_name='Virsraksts')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Bilde')),
                ('slug', models.SlugField(blank=True, help_text='Ievadiet URL draudzīgu nosaukumu.', unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('options', models.TextField(blank=True, help_text='Ievadiet opcijas kā sarakstu ar komatiem')),
                ('options_lv', models.TextField(blank=True, help_text='Ievadiet opcijas kā sarakstu ar komatiem', null=True)),
                ('options_en', models.TextField(blank=True, help_text='Ievadiet opcijas kā sarakstu ar komatiem', null=True)),
                ('front_image_with_background', models.ImageField(blank=True, upload_to='products/', verbose_name='Priekšējā bilde ar fonu')),
                ('front_image_not_background', models.ImageField(blank=True, upload_to='products/', verbose_name='Priekšējā bilde bez fona')),
                ('back_image_with_background', models.ImageField(blank=True, upload_to='products/', verbose_name='Aizmugurējā bilde ar fonu')),
                ('back_image_not_background', models.ImageField(blank=True, upload_to='products/', verbose_name='Aizmugurējā bilde bez fona')),
                ('front_image_coords', models.JSONField(blank=True, null=True)),
                ('back_image_coords', models.JSONField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Produkts',
                'verbose_name_plural': 'Produkti',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Vērtējums',
                'verbose_name_plural': 'Vērtējumi',
            },
        ),
    ]
