# Generated by Django 4.2.7 on 2024-08-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.designs'),
        ),
    ]
