# Generated by Django 4.2.7 on 2024-08-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
    ]
