# Generated by Django 4.2.7 on 2024-08-10 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_rating_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='order',
            new_name='design',
        ),
    ]
