# Generated by Django 4.2.7 on 2024-08-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_alter_designs_options_remove_designs_product_color'),
        ('Product', '0003_rename_order_rating_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
