# Generated by Django 4.2.7 on 2023-11-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_description_en_product_description_lv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button_title',
            field=models.CharField(default='d', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
