# Generated by Django 4.2.7 on 2023-11-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_button_title_en_product_button_title_lv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='button_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='button_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='button_title_lv',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
