"""
Django settings for ecomerce project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v1fiaup#2ni$7o)+u(uzkc9n$((#nrayt9__52wtm#651%-tpj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['www.mafia.lat', '104.248.195.146', 'mafia.lat', 'https://mafia.lat']

CSRF_COOKIE_SECURE = False
CSRF_TRUSTED_ORIGINS = ['https://www.mafia.lat', 'https://mafia.lat']

# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'jazzmin',
    'cart',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'colorfield',
    'django.contrib.staticfiles',
    'ckeditor',
    "phonenumber_field",
    'ckeditor_uploader',
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecomerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'cart.context_processor.cart_total_amount',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecomerce.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'urban_prod',
        'USER': 'u_urban',
        'PASSWORD': '123',
        'HOST': 'localhost',
        'PORT': '',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

abspath = lambda *p: os.path.abspath(os.path.join(*p))

PROJECT_ROOT = abspath(os.path.dirname(__file__))

MEDIA_ROOT = abspath(PROJECT_ROOT, 'media')
MEDIA_URL = '/media/'

AUTH_USER_MODEL = 'home.user'

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'lv-lv'

TIME_ZONE = 'Etc/GMT+2'

USE_I18N = True

USE_TZ = True

gettext = lambda s: s
LANGUAGES = (
    ('lv', gettext('Latvian')),
    ('en', gettext('English')),
)

MODELTRANSLATION_DEFAULT_LANGUAGE = 'lv'
MODELTRANSLATION_LANGUAGES = ('lv', 'en')

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
#STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"),]
# Default primary key field type
STATIC_ROOT = '/home/urban/Printing/static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    "language_chooser": True
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'mafiagameeee@gmail.com'
EMAIL_HOST_PASSWORD = 'hjmyxkzttzahgfib'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'mafiagameeee@gmail.com'

try:
    from ecomerce.local_settings import *
except ImportError:
    pass

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'height': 300,
        'width': 600,
    'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Flash', 'Table', 'HorizontalRule'],
            ['TextColor', 'BGColor'],
            ['Smiley', 'SpecialChar'], ['Source'],
            ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
            ['NumberedList','BulletedList'],
            ['Indent','Outdent'],
            ['Maximize'],
            ['Styles', 'Format', 'Font', 'FontSize'],
        ]
    },
}

JAZZMIN_SETTINGS = {
    'site_title': 'Design',
    'site_header': 'Design',
    'welcome_sign': 'Welcome',
    'show_sidebar': True,
    "language_chooser": True,
    "language": "lv",
    'navigation_expanded': True,
    'hide_apps': ["""'sites'"""],
    'show_ui_builder': False,
    "related_modal_active": True,
    'topmenu_links': [],
    'usermenu_links': [],
    'theme': 'home',
'icons': {
    'app.Model': 'fas fa-icon',
    'auth.User': 'fas fa-user',
    'home.Product': 'fas fa-shopping-bag',
    'home.CustomDesign': 'fas fa-cogs',
    'home.ContactMessage': 'fas fa-envelope',
    'home.Contact': 'fas fa-address-book',
    'home.user': 'fas fa-user',  
    'home.Price': 'fas fa-dollar-sign', 
    'home.Product_list': 'fas fa-list',  
    'home.GiftCode': 'fas fa-gift',  
},
}

CART_SESSION_ID = 'cart'
