# Generated by Django 4.2.7 on 2024-07-27 19:38

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ievadiet kategorijas nosaukumu.', max_length=100, unique=True, verbose_name='Virsraksts')),
                ('title_lv', models.CharField(help_text='Ievadiet kategorijas nosaukumu.', max_length=100, null=True, unique=True, verbose_name='Virsraksts')),
                ('title_en', models.CharField(help_text='Ievadiet kategorijas nosaukumu.', max_length=100, null=True, unique=True, verbose_name='Virsraksts')),
                ('slug', models.SlugField(blank=True, help_text='Ievadiet URL draudzīgu nosaukumu.', unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Bilde')),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorijas',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'Krāsa',
                'verbose_name_plural': 'Krāsas',
            },
        ),
        migrations.CreateModel(
            name='CustomDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Virsraksts')),
                ('title_lv', models.CharField(max_length=100, null=True, verbose_name='Virsraksts')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Virsraksts')),
                ('description', models.TextField(verbose_name='Apraksts')),
                ('description_lv', models.TextField(null=True, verbose_name='Apraksts')),
                ('description_en', models.TextField(null=True, verbose_name='Apraksts')),
                ('additional_notes', models.TextField(verbose_name='Papildu piezīmes')),
                ('additional_notes_lv', models.TextField(null=True, verbose_name='Papildu piezīmes')),
                ('additional_notes_en', models.TextField(null=True, verbose_name='Papildu piezīmes')),
                ('image', models.ImageField(upload_to='page/', verbose_name='Bilde')),
            ],
            options={
                'verbose_name': 'Pielāgots dizains',
                'verbose_name_plural': 'Pielāgoti dizaini',
            },
        ),
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unlimited_usage', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dāvanu kods',
                'verbose_name_plural': 'Dāvanu kodi',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_product', models.BooleanField(default=False)),
                ('allow_publish', models.BooleanField(default=False)),
                ('front_image', models.ImageField(blank=True, upload_to='designs/')),
                ('back_image', models.ImageField(blank=True, upload_to='designs/')),
                ('product_amount', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('average_rating', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Gaida apstiprinājumu'), ('PROCESSING', 'Apstrāde'), ('SHIPPED', 'Nosūtīts'), ('DELIVERED', 'Piegādāts'), ('CANCELLED', 'Atcelts')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Izmērs',
                'verbose_name_plural': 'Izmēri',
            },
        ),
        migrations.CreateModel(
            name='TextList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('font', models.CharField(blank=True, max_length=50)),
                ('text_size', models.CharField(blank=True, max_length=25)),
                ('text_color', models.CharField(blank=True, max_length=20)),
                ('order_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vērtējums',
                'verbose_name_plural': 'Vērtējumi',
            },
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_products', to='home.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ievadiet produkta nosaukumu.', max_length=100, unique=True, verbose_name='Virsraksts')),
                ('title_lv', models.CharField(help_text='Ievadiet produkta nosaukumu.', max_length=100, null=True, unique=True, verbose_name='Virsraksts')),
                ('title_en', models.CharField(help_text='Ievadiet produkta nosaukumu.', max_length=100, null=True, unique=True, verbose_name='Virsraksts')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Bilde')),
                ('slug', models.SlugField(blank=True, help_text='Ievadiet URL draudzīgu nosaukumu.', unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('options', models.TextField(blank=True, help_text='Ievadiet opcijas kā sarakstu ar komatiem')),
                ('options_lv', models.TextField(blank=True, help_text='Ievadiet opcijas kā sarakstu ar komatiem', null=True)),
                ('options_en', models.TextField(blank=True, help_text='Ievadiet opcijas kā sarakstu ar komatiem', null=True)),
                ('front_image_with_background', models.ImageField(blank=True, upload_to='products/', verbose_name='Priekšējā bilde ar fonu')),
                ('front_image_not_background', models.ImageField(blank=True, upload_to='products/', verbose_name='Priekšējā bilde bez fona')),
                ('back_image_with_background', models.ImageField(blank=True, upload_to='products/', verbose_name='Aizmugurējā bilde ar fonu')),
                ('back_image_not_background', models.ImageField(blank=True, upload_to='products/', verbose_name='Aizmugurējā bilde bez fona')),
                ('front_image_coords', models.JSONField(blank=True, null=True)),
                ('back_image_coords', models.JSONField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('available_colors', models.ManyToManyField(blank=True, related_name='products', to='home.color')),
                ('available_sizes', models.ManyToManyField(blank=True, related_name='products', to='home.size')),
                ('categories', models.ManyToManyField(related_name='products', to='home.category')),
            ],
            options={
                'verbose_name': 'Produkts',
                'verbose_name_plural': 'Produkti',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.color'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.size'),
        ),
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(blank=True)),
                ('order_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
    ]
