# Generated by Django 4.2.7 on 2024-09-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseproduct',
            name='purchase',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseProduct',
        ),
    ]
