# Generated by Django 4.2.7 on 2024-07-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_size',
        ),
    ]
