# Generated by Django 4.2.7 on 2023-12-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='options_en',
            field=models.TextField(blank=True, help_text='Ievadiet opcijas kā sarakstu ar komatiem', null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='options_lv',
            field=models.TextField(blank=True, help_text='Ievadiet opcijas kā sarakstu ar komatiem', null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='title_lv',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
