# Generated by Django 4.2.7 on 2024-07-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_order_product_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='product_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.size'),
        ),
    ]
