# Generated by Django 4.2.7 on 2024-10-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_purchaseproduct_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftCode',
        ),
    ]
