# Generated by Django 4.2.7 on 2024-03-19 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_product', models.BooleanField(default=False)),
                ('allow_publish', models.BooleanField(default=False)),
                ('front_image', models.ImageField(blank=True, upload_to='users_products/')),
                ('back_image', models.ImageField(blank=True, upload_to='users_products/')),
                ('product_amount', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.color')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.size')),
            ],
        ),
        migrations.CreateModel(
            name='TextList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('font', models.CharField(blank=True, max_length=50)),
                ('text_size', models.IntegerField(blank=True)),
                ('text_color', models.CharField(blank=True, max_length=20)),
                ('order_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='upload_images/')),
                ('order_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
    ]
