# Generated by Django 4.2.7 on 2023-11-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_button_title_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button_title_en',
            field=models.CharField(default='d', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='button_title_lv',
            field=models.CharField(default='d', max_length=100, null=True),
        ),
    ]
