# Generated by Django 4.2.7 on 2024-03-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_order_product_images_and_more'),
        ('home', '0004_order_textlist_imagelist'),
    ]

    operations = [
    ]
