# Generated by Django 4.2.7 on 2024-08-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_rating_order'),
        ('home', '0005_remove_product_available_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='author',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='textlist',
            name='order_text',
        ),
        migrations.DeleteModel(
            name='ImageList',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='TextList',
        ),
    ]
