# Generated by Django 4.2.7 on 2023-12-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_list_average_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.TextField(blank=True, help_text='Ievadiet opcijas kā sarakstu ar komatiem'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
