# Generated by Django 4.2.7 on 2023-11-09 21:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_button_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button_color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
    ]
