# Generated by Django 4.2.7 on 2024-03-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_order_product_color_alter_order_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlist',
            name='text',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
