# Generated by Django 4.2.7 on 2023-12-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_product_list_price_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='options_en',
            field=models.TextField(blank=True, help_text='Ievadiet opcijas kā sarakstu ar komatiem', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='options_lv',
            field=models.TextField(blank=True, help_text='Ievadiet opcijas kā sarakstu ar komatiem', null=True),
        ),
    ]
