# Generated by Django 4.2.7 on 2024-03-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_textlist_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlist',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='textlist',
            name='text_size',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
