# Generated by Django 4.2.7 on 2024-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_giftcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcode',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
