# Generated by Django 4.2.7 on 2024-01-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_giftcode_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcode',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcode',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
