# Generated by Django 4.2.7 on 2023-12-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_contactmessage_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
