# Generated by Django 4.2.7 on 2024-01-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_giftcode_end_date_giftcode_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcode',
            name='max_usage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcode',
            name='unlimited_usage',
            field=models.BooleanField(default=False),
        ),
    ]
