# Generated by Django 4.2.7 on 2023-12-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_contactmessage_admin_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='admin_attachment',
        ),
    ]
