# Generated by Django 4.2.7 on 2024-01-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_giftcode_max_usage_giftcode_unlimited_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftcode',
            old_name='max_usage',
            new_name='quantity',
        ),
    ]
