# Generated by Django 4.2.7 on 2024-03-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_imagelist_image_png'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelist',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
