# Generated by Django 4.2.7 on 2024-02-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='hello', help_text='Ievadiet URL draudzīgu nosaukumu.', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
