# Generated by Django 4.2.7 on 2024-09-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Jautājums')),
                ('answer', models.TextField(verbose_name='Atbilde')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Izveidots')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atjaunots')),
            ],
            options={
                'verbose_name': 'Biežāk uzdoto jautājumu',
                'verbose_name_plural': 'Biežāk uzdoto jautājumi',
                'ordering': ['created_at'],
            },
        ),
    ]
