# Generated by Django 4.2.7 on 2024-09-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Atbilde'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_lv',
            field=models.TextField(null=True, verbose_name='Atbilde'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Jautājums'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_lv',
            field=models.CharField(max_length=255, null=True, verbose_name='Jautājums'),
        ),
    ]
