# Generated by Django 4.2.7 on 2024-08-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgid', models.TextField()),
                ('msgstr', models.TextField(blank=True)),
                ('locations', models.TextField()),
                ('fuzzy', models.BooleanField(default=False)),
            ],
        ),
    ]
