# Generated by Django 4.2.7 on 2024-08-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='source_file',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
